In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np


In [2]:
data = pd.read_csv('input.csv', header=0)

data["Labeling"] = LabelEncoder().fit_transform(data["Labeling"])

print(data["Labeling"])



0     0
1     0
2     0
3     0
4     0
     ..
75    1
76    1
77    1
78    1
79    1
Name: Labeling, Length: 80, dtype: int32


In [3]:
X = data.drop(["Labeling"], axis=1).to_numpy()
o = np.ones((X.shape[0], 1))
np.concatenate([o, X], axis=1)

array([[1. , 5.4, 3.9, 1.7, 0.4],
       [1. , 4.6, 3.4, 1.4, 0.3],
       [1. , 5. , 3.4, 1.5, 0.2],
       [1. , 4.4, 2.9, 1.4, 0.2],
       [1. , 4.9, 3.1, 1.5, 0.1],
       [1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 4.8, 3.4, 1.6, 0.2],
       [1. , 4.8, 3. , 1.4, 0.1],
       [1. , 4.3, 3. , 1.1, 0.1],
       [1. , 5.8, 4. , 1.2, 0.2],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 5.1, 3.5, 1.4, 0.3],
       [1. , 5.7, 3.8, 1.7, 0.3],
       [1. , 5.1, 3.8, 1.5, 0.3],
       [1. , 5.4, 3.4, 1.7, 0.2],
       [1. , 5.1, 3.7, 1.5, 0.4],
       [1. , 4.6, 3.6, 1. , 0.2],
       [1. , 5.1, 3.3, 1.7, 0.5],
       [1. , 4.8, 3.4, 1.9, 0.2],
       [1. , 5. , 3. , 1.6, 0.2],
       [1. , 5. , 3.4, 1.6, 0.4],
       [1. , 5.2, 3.5, 1.5, 0.2],
       [1. , 5.2, 3.4, 1.4, 0.2],
       [1. , 4.7, 3.2, 1.6, 0.2],
       [1. , 4.8, 3.1, 1.6, 0.2],
       [1. , 5.4, 3.4, 1.5, 0.4],
       [1. , 5.2, 4.1, 1.5, 0.1],
       [1. , 5.5, 4.2, 1.4, 0.2],
       [1. , 4

In [5]:
Y = data["Labeling"].to_numpy()

In [6]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
def sigmoid(z):
    return 1. / (1+np.exp(-z))

def loss_function(y_hat, y):
    return (-y * np.log(y_hat) - (1 - y) * np.log(1 - y_hat))

def gradient(x, y_hat, y):
    return np.dot(x.T, (y_hat - y))

def predict(x, theta):    
    z = np.dot(x, theta)
    y_hat = sigmoid(z)
    return y_hat

def gradient_descent(x, y, theta, lr, epochs):
    for epoch in range(epochs):
        for i in range(x.shape[0]):
            xi=x[i]
            yi=y[i]
            y_hat=predict(xi, theta)
            loss = loss_function(y_hat, yi)
            grad = gradient(xi, y_hat, yi)
            theta = theta - lr * grad
    return theta       

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

theta =  np.random.uniform(size=X_train.shape[1])
theta = gradient_descent(X_train, Y_train, theta, 0.01, 1000)

In [16]:
theta

array([-1.15170825, -2.51751234,  4.35068839,  2.06747905])